#!C:\Users\DELL\Downloads\chatbot-2\End-To-End-Gemini-Project\venv1\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
